all:
    hosts:
        web01:
            ansible_host: private_ip_of machine_web01
            ansible_user: ec2-user
            ansible_ssh_private_key_file: clientkey.pem

########################################################
#Next config
all:
  hosts:
    respro-web01:
      ansible_host: 172.31.84.160
      ansible_user: ec2-user
      ansible_ssh_private_key_file: res-client.pem
    respro-web02:
      ansible_host: 172.31.82.133
      ansible_user: ec2-user
      ansible_ssh_private_key_file: res-client.pem
    respro-db01:
      ansible_host: 172.31.91.101
      ansible_user: ec2-user
      ansible_ssh_private_key_file: res-client.pem

  children:
    webservers:
      hosts:
        respro-web01:
        respro-web02:
    dbservers:
      hosts:
        respro-db01:
    n_virginia:
      children:
        webservers:
        dbservers:
